use crate::error::AppError;

/// Events flowing from the orchestrator and spawned LLM tasks to the TUI loop.
///
/// All events arrive via `tokio::sync::mpsc::UnboundedReceiver<AppEvent>`
/// and are dispatched in the main `tokio::select!` loop. The TUI never
/// blocks on LLM work — all LLM calls run in `tokio::spawn`ed tasks
/// and push results back through this channel.
///
/// # Lifecycle
///
/// - `WriterOutput` / `CriticOutput`: streaming chunks as they arrive.
/// - `WriterDone` / `CritiqueReady`: signals a turn has completed.
/// - `ApologyReady` / `ApologyTriggered`: apology bar state changes.
/// - `Error` / `CostWarning` / `LoopExhausted`: guard rails.
/// - `Shutdown`: user-requested exit via Ctrl+C or Esc/q.
#[derive(Debug)]
pub enum AppEvent {
    /// A chunk of token output from the Writer stream.
    WriterOutput(String),

    /// A chunk of token output from the Critic stream.
    CriticOutput(String),

    /// A complete Apology has been generated by the separate LLM call.
    ApologyReady(String),

    /// Writer completed its turn, reporting the total token count for the turn.
    WriterDone(u64),

    /// The Critic has finished a critique and is ready for the next round.
    CritiqueReady(u64),

    /// The Writer's output contained an `[APOLOGY]` marker, triggering the
    /// apology workflow.
    ApologyTriggered,

    /// Current apology cooldown remaining, in seconds.
    ///
    /// `Some(secs)` when an active cooldown is in effect; `None` when the
    /// cooldown has expired or no apology has occurred yet.
    ApologyCooldown(Option<u64>),

    /// An error occurred in a spawned task or the orchestrator.
    Error(AppError),

    /// The cost ceiling is approaching its limit.
    /// Fields: spent (total), limit (ceiling), per-agent costs in USD.
    CostWarning {
        spent: f64,
        limit: f64,
        writer_cost: f64,
        critic_cost: f64,
        apology_cost: f64,
    },

    /// The loop detection guard triggered — the output is repetitive and no
    /// further progress is expected.
    LoopExhausted,

    /// The user requested shutdown (Ctrl+C or Esc/q). All spawned tasks
    /// should wind down and the TUI should exit.
    Shutdown,
}
